{% set name = "isosurfaces" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/isosurfaces-{{ version }}.tar.gz
  sha256: 18aab4ec7148a8376097b49006ea0e9ec07e468fa5fc6133d7d9eef977fe384d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8

test:
  imports:
    - isosurfaces
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jared-hughes/isosurfaces
  summary: Construct isolines/isosurfaces over a 2D/3D scalar field defined by a function (not a uniform grid)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gauranshkumar
